name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%h %d %Y - %H:%M:%S')"

      - name: Update version.json file
        uses: jossef/action-set-json-field@v1
        with:
          file: nightly/version.json
          field: version
          value: ${{ steps.date.outputs.date }}
      
      - name: Copy firmware to nightly folder
        run: |
          cp .pio/build/esp32doit-devkit-v1/firmware.bin nightly/firmware.bin
          git add . -A
          git commit -m "nightly build"
          git push

      # - name: Test PlatformIO Project
      #   run: pio remote  test

      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware.bin 
          path: |
            .pio/build/esp32doit-devkit-v1/firmware.bin
